name: Create New Release

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      
      - name: Select Latest Xcode
        run: |
          sudo xcode-select -s /Applications/Xcode_16.2.app/Contents/Developer
          xcodebuild -version
          xcodebuild -showsdks
          echo "Available iOS SDKs:"
          xcodebuild -showsdks | grep iphoneos

      - name: Clean Build Environment
        run: |
          make clean || true
          rm -rf ~/Library/Developer/Xcode/DerivedData
          rm -rf ~/Library/Caches/com.apple.dt.Xcode

      - name: Compile Portal
        run: |
          agvtool new-version -all $(git rev-list --count HEAD)
          make
          mkdir upload
          mv packages/* upload/

      - name: Get Version
        id: get_version
        run: |
          VERSION=$(/usr/libexec/PlistBuddy -c "Print CFBundleShortVersionString" Payload/*.app/Info.plist)
          echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: Portal v${{ steps.get_version.outputs.VERSION }}
          tag_name: v${{ steps.get_version.outputs.VERSION }}
          body: |
            Latest stable release to download

            Full Changelog: https://github.com/${{ github.repository }}/commits/v${{ steps.get_version.outputs.VERSION }}
          files: |
            upload/*ipa
          fail_on_unmatched_files: true
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
